### ISSUE TITLE
小疑问

### ISSUE THREAD

**Issue by NowLoadY** [flpsite/Q-learning-for-path-planning#1]
一些较成熟的切片软件考虑到了各种像喷头挤出回抽或是擦嘴的一些细节动作，强化学习我觉得特别赞成，不够不知道这种细节动作会包含在Gcode里面吗

**Comment by flpsite** [comment]
回抽和擦嘴这些细节暂未考虑

**Comment by NowLoadY** [comment]
还是超赞 感觉很创新（小白的发言
以后学了强化学习我也要试试（以后的以后

**Comment by flpsite** [comment]
谢谢，其实我也是受前辈的启发，才有这样的想法，期待你未来的工作。
